# Generated by Django 5.1.6 on 2025-03-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_address_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='owner',
        ),
    ]
