# Generated by Django 5.1.6 on 2025-03-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0002_remove_order_customer_order_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="customer",
        ),
    ]
