# Generated by Django 5.1.6 on 2025-03-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0003_rename_user_order_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "get_latest_by": ["order_date"],
                "ordering": ["-order_date"],
                "permissions": [("can_view_statistics", "Can view statistics")],
            },
        ),
    ]
